format_version: v1.0
configName: e54_have_fun
folderName: same54
frameworkPath: ..\..\Users\mruizes\Harmony3
processor: ATSAME54P20A
projectName: same54_fun
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME54_DFP\3.5.87\atdf\ATSAME54P20A.atdf
